services:
  microsoft-rewards-script:
    build: .
    container_name: netsky
    environment:
      - TZ=${TZ}
      - NODE_ENV=${NODE_ENV}  # Use the environment variable
      - HEADLESS=${HEADLESS}   # Use the environment variable
      - CRON_START_TIME=${CRON_START_TIME}
      - RUN_ON_START=${RUN_ON_START}
      - DATA_PATH=${DATA_PATH} # Use the environment variable
    volumes:
      ### Use the environment variable for the file paths
      - ${DATA_PATH}/accounts.json:/usr/src/microsoft-rewards-script/dist/accounts.json
      - ${DATA_PATH}/config.json:/usr/src/microsoft-rewards-script/dist/config.json
      - ${DATA_PATH}/sessions:/usr/src/microsoft-rewards-script/dist/browser/sessions # Optional, saves your login session
    deploy:
      resources:
        limits:
          memory: 2048M
    restart: unless-stopped
